site_name: ArPI - Home Security System
site_url: https://www.arpi-security.info
site_description: Documentation for the ArPI Home Security System
site_author: Gábor Kovács
copyright: Copyright © 2020 - ArPI Home Security

repo_name: ArPI - documentation
repo_url: https://github.com/ArPIHomeSecurity/arpi_documentation

theme:
    name: material
    features:
        - navigation.tabs
        - navigation.top
    logo: assets/argus-eye-30.png
    favicon: assets/argus-eye-16.png
    palette:
        primary: indigo
        accent: orange

extra_css:
  - styles/arpi.css

extra_javascript:
  - 'assets/jquery.js'

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - footnotes
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format


nav:
    - Home: index.md
    - End user: 
        - Manual: end_users/index.md
        - Users: end_users/user.md
        - Administrators: end_users/admin.md
        - Glossary: end_users/glossary.md

        # Help pages
        - Register: end_users/register.md
        - Login: end_users/login.md

        - Alert history: end_users/alert_history.md
        - Zones: end_users/zones.md
        - Sensors: end_users/sensors.md
        - Syren: end_users/syren.md
        - Keypad: end_users/keypad.md
        - Notifications: end_users/notifications.md
        - Network: end_users/network.md
        - Clock: end_users/clock.md
        - Users: end_users/users.md

    - Security Engineers:
        - Installation: security_engineers/index.md
        - Restore access: security_engineers/restore_access.md
    - Developers: 
        - Overview: developers/index.md
        - Backend: developers/backend.md
        - Web application: developers/web_application.md
        - Installation: developers/installation.md
        - Deployment: developers/deployment.md
        - Testing: developers/testing.md
    - About: about.md