site_name: ArPI - Home Security System
site_url: https://www.arpi-security.info
site_description: Documentation for the ArPI Home Security System
site_author: Gábor Kovács
copyright: Copyright © 2020 - ArPI Home Security

repo_name: ArPI - documentation
repo_url: https://github.com/ArPIHomeSecurity/arpi_documentation

theme:
    name: material
    features:
        - tabs
    logo: assets/argus-eye-30.png
    favicon: assets/argus-eye-16.png
    palette:
        primary: indigo
        accent: orange

extra_css:
  - styles/arpi.css

extra_javascript:
  - 'assets/jquery.js'

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - footnotes
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format


nav:
    - Home: index.md
    - End user: 
        - Manual: end_users/index.md
        - Users: end_users/user.md
        - Administrators: end_users/admin.md
        - Glossary: end_users/glossary.md
    - Security Engineers:
        - Security Engineers: security_engineers/index.md
    - Developers: 
        - Overview: developers/index.md
        - Backend: developers/backend.md
        - Web application: developers/web_application.md
        - Installation: developers/installation.md
        - Deployment: developers/deployment.md
    - About:
        About: about.md