site_name: ArPI - Home Security System
site_url: https://docs.arpi-security.info/en/latest/
site_description: Documentation for the ArPI Home Security System
site_author: Gábor Kovács
copyright: Copyright © 2024 - ArPI Home Security

repo_name: ArPI - documentation
repo_url: https://github.com/ArPIHomeSecurity/arpi_documentation

theme:
    name: material
    features:
        - navigation.tabs
        - navigation.top
    logo: assets/argus-eye-30.png
    favicon: assets/argus-eye-16.png
    palette:
        primary: indigo
        accent: orange

extra_css:
  - styles/arpi.css

extra_javascript:
  - 'assets/jquery.js'

plugins:
  - search
  - glightbox

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - footnotes
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - attr_list # for images


nav:
    - Home: index.md
    - End user:
        - Manual: end_users/index.md
        - Register: end_users/register.md
        - Login: end_users/login.md
        - Events: end_users/events.md
        - Glossary: end_users/glossary.md

        # Help pages for the application
        - Configurations:
            - Areas: end_users/areas.md
            - Zones: end_users/zones.md
            - Sensors: end_users/sensors.md
            - Outputs: end_users/outputs.md
            - Syren: end_users/syren.md
            - Keypad: end_users/keypad.md
            - Notifications: end_users/notifications.md
            - Network: end_users/network.md
            - Clock: end_users/clock.md
            - Users: end_users/users.md

    - Security Engineers:
        - Overview: security_engineers/index.md
        - Installation: security_engineers/installation.md
        - Restore access: security_engineers/restore_access.md
        - Reset database: security_engineers/reset_database.md
        - Generate hash: security_engineers/generate_hash.md
        - SSH: security_engineers/ssh.md
        - System logs: security_engineers/system_logs.md

    - Developers:
        - Overview: developers/index.md
        - Backend: developers/backend.md
        - Web application: developers/web_application.md
        - Installation: developers/installation.md
        - Deployment: developers/deployment.md
        - Testing: developers/testing.md
        - Logging: developers/logging.md
        - Simulator: developers/simulator.md

    - About: about.md

extra:
  social:
    - icon: fontawesome/brands/slack 
      link: https://arpi-security.slack.com/