site_name: ArPI - Home Security System
theme:
    name: material
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true

nav:
    - 'Home': 'index.md'
    - 'End user': 'end_users/index.md'
    - 'Security Engineers': 'security_engineers/index.md'
    - 'Developers': 'developers/index.md'
    - 'About': 'about.md'